# Generated by Django 4.2.30 on 2026-07-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_date',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
