# Generated by Django 4.2.30 on 2026-07-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0002_remove_blog_album_name_remove_blog_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
